### ISSUE TITLE
'pocketbase' does not appear to be a git repository

### ISSUE THREAD

**Issue by peteror** [AlexR1712/dokku-pocketbase#3]
Hi,
I'm quite new to dokku and pocketbase, so I tried to deploy this thing using the instructions in the readme file. 

After git push dokku main, I got this error: 

fatal: 'pocketbase' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

should I clone this dokku-pocketbase repo or the actual pocketbase repo? This repo seems to only have a dockerfile inside, which leaves me a bit confused on what this thing actually does. 

thanks!

**Comment by AlexR1712** [comment]
Looks like do you have a issue on your git remote definition try removing the remote and add it again.

### Example
```plain
git remote add dokku dokku@IPorDomainOfYourDokku:appname

# or in this case

git remote add dokku dokku@IPorDomainOfYourDokku:pocketbase

```

@peteror

**Comment by peteror** [comment]
I still have the same error... 

In the first step: https://github.com/your-repo/dokku-pocketbase.git - which repo should I clone? this one? (blockshiftnetwork/dokku-pocketbase) the pocketbase one? 

the error message suggests it's looking for a repo called pocketbase, but in the first step I cloned the dokku-pockebase repo

**Comment by peteror** [comment]
ok, I figured out, my username was not dokku, whch makes dokku pushes fail .. 🤦
